### ISSUE TITLE
Update Interface

### ISSUE THREAD

**Issue by nooraniali17** [nooraniali17/Afterdark#1]
One change I will make to our group project Afterdark is a redesigned user interface. I will try to simplify the main menu and try to get rid of a lot of the empty space that is currently there. As can be seen by the screenshot attached below, there is a lot of unused space on the bottom 3/4's of the main menu screen. The font sizes will also be increased to make the menu more balanced and in addition to that I will try to simplify the different screens that pop up once something is clicked. Instead of having to click on various things to access certain menu options and then being redirected to a new screen I will try to place the most important settings all on the main menu. For example, instead of having the Settings icon I will just place the settings right next to the other icons that can be clicked on. This will happen by editing a few of the menu classes that our group had made before. The most changes will happen in MenuPane.java since that is where most of the content will be going to from the other various menus. The other classes that will need to change are the Settings.java and Controls.java classes because instead of leaving those the same I will have to incorporate them into the MenuPane.java class.
![main menu](https://user-images.githubusercontent.com/23248146/51420390-7cfb1080-1b46-11e9-9fbd-9db7778cbf25.png)

**Comment by onzfonz** [comment]
Hey Ali, this is one issue, please provide 2 more.  I would like to see a feature or improvement that would mean you would need to change a few different classes and methods.  Let me know if you have any questions via email.  Thanks!
