### ISSUE TITLE
Create Stopwatch for Competition

### ISSUE THREAD

**Issue by nooraniali17** [nooraniali17/Afterdark#3]
The third change that I will make to our group project will encourage some friendly competition amongst different players. As of right now there is no way to quantify how someone does in the particular level we have made for our game. As a result, I will create a stopwatch that starts as soon as the level starts. Once the playable character successfully completes the level then the stopwatch will stop and display the final time on the top of the screen to provide information for the player so that way they can try and beat their previous time in the future. In order to do this, I will have to make changes to our Game.java class because that is where I will have to actually add the stopwatch label. The next class that will need changes is the GButton.java class because this is the class where I will be able to make the actual format changes needed to display the stopwatch clearly during gameplay. The next class I will need to change is the GameWon.java class because when the player beats the level, I will need to display the time it took for them to actually finish the level. After making these changes the stopwatch should work well and add another aspect to our game.

**Comment by onzfonz** [comment]
Can we also add it so that you store the stopwatch time in a file so you have like the fastest time somewhere?  That can be your last part of this feature.  Let's go with this one.

**Comment by nooraniali17** [comment]
The stopwatch feature has been built and it can be seen at the top of the screen during gameplay. The stopwatch will count upwards every second for the duration that it takes the player to reach the end of the level. If the player does not make it to the end of the level then no high score is shown, but if the level is completed the game won menu will show up presenting the time it took to complete that level. Underneath that is a button to view the fastest time for that level, which once clicked on will open the text file with the fastest time.
